version: "3.3"
services:
  mongo_db:
    image: mongo:5.0
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/docker-entrypoint-initdb.d
      
  python_server:
    build: ./python
    depends_on:
      - "mongo_db"
    container_name: python_server
    ports:
      - 5000:5000

  nginx_server:
    build: ./nginx
    depends_on:
      - "python_server"
    volumes:
      - ./nginx:/usr/share/nginx/html
    ports:
      - 3000:3000